### ISSUE TITLE
-_-

### ISSUE THREAD

**Issue by AlanZhangv1** [CreativeCimmons/ORB-SLAM-Android-app#1]
hello, have you finished it? I'm working on it too.

**Comment by CreativeCimmons** [comment]
Hello Alan,,
I am creating gradle build for it be run on android ndk. I haven't yet completed it. What are you working upto?
Thanks
Dinesh 

    On Monday, 25 January 2016 10:12 AM, AlanZhangv1 <notifications@github.com> wrote:
 

 hello, have you finished it? I'm working on it too—
